# HTTP Properties configured
http.listener.port=8081c
# AutoDiscovery ID
api.id=20981191

# Salesforce Config
salesforce.username=ramakrishnakapa6.58728c8b7fd5@agentforce.com
salesforce.password=![E41zEMr1TspJ7q50qH/4kQ==]